#!/bin/bash
# Generated by Powerlevel10k configuration wizard (customized for Nubank).
# Based on romkatv/powerlevel10k config. Requires Nerd Font.
#
# Tip: To re-run the wizard, delete this file and restart zsh.
# Managed by DevTools

# Temporarily change options for this file only.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

# shellcheck disable=SC1073,SC1072
() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options.
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh >= 5.1 is required.
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  # ==========================================
  # PROMPT LAYOUT
  # ==========================================

  # Left prompt segments
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon
    dir
    vcs
    virtualenv
    kubecontext
    prompt_char
  )

  # Right prompt segments
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status
    command_execution_time
    background_jobs
    node_version
    java_version
    go_version
    clojure_version
    aws
    time
  )

  # ==========================================
  # GENERAL SETTINGS
  # ==========================================

  typeset -g POWERLEVEL9K_MODE='nerdfont-v3'
  typeset -g POWERLEVEL9K_ICON_PADDING=moderate

  # Prompt connection
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX=
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=

  # Transient prompt (clean scrollback)
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=off

  # Instant prompt mode
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

  # Hot reload
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=false

  # ==========================================
  # OS ICON
  # ==========================================

  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND='#530087'

  # ==========================================
  # DIRECTORY (Nubank Purple)
  # ==========================================

  typeset -g POWERLEVEL9K_DIR_BACKGROUND='#820AD1'
  typeset -g POWERLEVEL9K_DIR_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=none
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true

  # Directory state colors
  typeset -g POWERLEVEL9K_DIR_HOME_BACKGROUND='#820AD1'
  typeset -g POWERLEVEL9K_DIR_HOME_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='#820AD1'
  typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='#820AD1'
  typeset -g POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_DIR_ETC_BACKGROUND='#820AD1'
  typeset -g POWERLEVEL9K_DIR_ETC_FOREGROUND='#FFFFFF'

  # ==========================================
  # VCS (Git)
  # ==========================================

  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND='#2D8A3E'
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='#A855F7'
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='#D4A017'
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#000000'
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND='#EF5350'
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND='#555555'
  typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND='#FFFFFF'

  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '
  typeset -g POWERLEVEL9K_VCS_COMMIT_ICON='@'

  # VCS status formatting
  typeset -g POWERLEVEL9K_VCS_{STAGED,UNSTAGED,UNTRACKED,CONFLICTED,COMMITS_AHEAD,COMMITS_BEHIND}_MAX_NUM=-1
  typeset -g POWERLEVEL9K_VCS_BACKENDS=(git)

  # ==========================================
  # PROMPT CHARACTER (Nubank Purple)
  # ==========================================

  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='#A855F7'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND='#EF5350'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='V'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true

  # ==========================================
  # STATUS (Exit Code — right prompt)
  # ==========================================

  typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true

  # OK — hidden on success for a clean prompt
  typeset -g POWERLEVEL9K_STATUS_OK=false
  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND='#388E3C'

  # OK pipe — show success in pipelines
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND='#388E3C'
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION='✔'

  # Error — shows exit code with red background
  typeset -g POWERLEVEL9K_STATUS_ERROR=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND='#D32F2F'
  typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✘'

  # Error signal (e.g. SIGSEGV)
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND='#D32F2F'
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION='✘'
  typeset -g POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false

  # Error pipe
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND='#D32F2F'
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION='✘'

  # ==========================================
  # COMMAND EXECUTION TIME
  # ==========================================

  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='#B8860B'
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'

  # ==========================================
  # BACKGROUND JOBS
  # ==========================================

  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='#1976D2'

  # ==========================================
  # NODE VERSION
  # ==========================================

  typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_NODE_VERSION_BACKGROUND='#2E7D32'
  typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true

  # ==========================================
  # JAVA VERSION
  # ==========================================

  typeset -g POWERLEVEL9K_JAVA_VERSION_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_JAVA_VERSION_BACKGROUND='#E65100'
  typeset -g POWERLEVEL9K_JAVA_VERSION_PROJECT_ONLY=true
  typeset -g POWERLEVEL9K_JAVA_VERSION_FULL=false

  # ==========================================
  # GO VERSION
  # ==========================================

  typeset -g POWERLEVEL9K_GO_VERSION_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_GO_VERSION_BACKGROUND='#00ADD8'
  typeset -g POWERLEVEL9K_GO_VERSION_PROJECT_ONLY=true

  # ==========================================
  # CLOJURE VERSION
  # ==========================================

  typeset -g POWERLEVEL9K_CLOJURE_VERSION_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_CLOJURE_VERSION_BACKGROUND='#5881D8'
  typeset -g POWERLEVEL9K_CLOJURE_VERSION_PROJECT_ONLY=true

  # ==========================================
  # AWS
  # ==========================================

  typeset -g POWERLEVEL9K_AWS_SHOW_ON_COMMAND='aws|terraform|pulumi|terragrunt'
  typeset -g POWERLEVEL9K_AWS_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_AWS_BACKGROUND='#E68A00'

  # ==========================================
  # TIME
  # ==========================================

  typeset -g POWERLEVEL9K_TIME_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_TIME_BACKGROUND='#530087'
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=true

  # ==========================================
  # VIRTUALENV (Python)
  # ==========================================

  typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND='#306998'
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
  typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV=false
  typeset -g POWERLEVEL9K_VIRTUALENV_{PYENV_PROMPT_,PYENV_,}CONTENT_EXPANSION=

  # ==========================================
  # KUBECONTEXT (Kubernetes)
  # ==========================================

  typeset -g POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND='kubectl|helm|kubens|kubectx|oc|istioctl|kogito|k9s|helmfile|flux|fluxctl|stern|kubeseal|skaffold|kubent|kubelogin|kustomize|argocd'
  typeset -g POWERLEVEL9K_KUBECONTEXT_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_KUBECONTEXT_BACKGROUND='#326CE5'

  # Safety coloring: production contexts get red, staging gets amber
  typeset -g POWERLEVEL9K_KUBECONTEXT_CLASSES=(
    '*-prod*'  PROD
    '*-stg*'   STG
    '*'        DEFAULT
  )
  typeset -g POWERLEVEL9K_KUBECONTEXT_PROD_BACKGROUND='#D32F2F'
  typeset -g POWERLEVEL9K_KUBECONTEXT_PROD_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_KUBECONTEXT_STG_BACKGROUND='#E68A00'
  typeset -g POWERLEVEL9K_KUBECONTEXT_STG_FOREGROUND='#FFFFFF'
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_BACKGROUND='#326CE5'
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND='#FFFFFF'

  # ==========================================
  # SEPARATORS / STYLING
  # ==========================================

  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uE0B1'
  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\uE0B3'
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B0'
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B2'
  typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B0'
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B2'
  typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''

  typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=

  # ==========================================
  # FINALISE
  # ==========================================

  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  # If p10k is already loaded, reload configuration.
  # This works even with POWERLEVEL9K_DISABLE_HOT_RELOAD=true.
  (( ! $+functions[p10k] )) || p10k reload
}

# Tell `p10k configure` which file it should overwrite.
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
